apiVersion: skaffold/v2beta6
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: flrs/sd_covid_dashboard_dashboard
      context: dashboard
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'app.ipynb'
            dest: '/app/app.ipynb'
          - src: './src'
            dest: '/app/src'
          - src: './data'
            dest: '/app/data'
    - image: flrs/sd_covid_dashboard_crawler
      context: crawler
      docker:
        dockerfile: Dockerfile
deploy:
  kustomize:
    paths:
      - k8s/overlays/dev