apiVersion: skaffold/v2beta6
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: flrs/sd_covid_dashboard_dashboard
      context: dashboard
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'app.ipynb'
            dest: '/app/app.ipynb'
          - src: './src'
            dest: '/app/src'
          - src: './data'
            dest: '/app/data'
    - image: flrs/sd_covid_dashboard_crawler
      context: crawler
      docker:
        dockerfile: Dockerfile
#deploy:
#  kustomize:
#    paths:
#      - k8s/overlays/dev
deploy:
 kubectl:
      manifests:
        - k8s/overlays/dev/dashboard-deployment.yaml
        - k8s/overlays/dev/dashboard-service.yaml
        - k8s/overlays/dev/crawler-cronjob.yaml
        - k8s/overlays/dev/postgres-deployment.yaml
        - k8s/overlays/dev/postgres-secrets.yaml
        - k8s/overlays/dev/postgres-service.yaml
        - k8s/overlays/dev/postgres-volume.yaml
        - k8s/overlays/dev/postgres-volume_claim.yaml
portForward:
- resourceType: deployment
  resourceName: dashboard
  port: 8866
  localPort: 8866
