apiVersion: skaffold/v2beta6
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: flrs/sd_covid_dashboard_dashboard
      context: dashboard
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'app.ipynb'
            dest: '/app/'
          - src: './src'
            dest: '/app/src'
          - src: './data'
            dest: '/app/data'
    - image: flrs/sd_covid_dashboard_crawler
      context: crawler
      docker:
        dockerfile: Dockerfile
deploy:
 kubectl:
      manifests:
        - k8s/overlays/dev/dashboard-deployment.yaml
        - k8s/overlays/dev/dashboard-service.yaml
        - k8s/overlays/dev/crawler-cronjob.yaml
        - k8s/overlays/dev/crawler-seedjob.yaml
        - k8s/overlays/dev/postgres-deployment.yaml
        - k8s/overlays/dev/postgres-volume.yaml
        - k8s/overlays/dev/postgres-volume_claim.yaml
        - k8s/overlays/dev/postgres-secrets.yaml
        - k8s/overlays/dev/postgres-service.yaml