apiVersion: cronjobber.hidde.co/v1alpha1
kind: TZCronJob
metadata:
  name: crawler-cronjob
  namespace: dashboard
spec:
  schedule: "0 18 * * *"
  timezone: "America/Los_Angeles"
  jobTemplate:
    spec:
      template:
        spec:
          nodeSelector:
            cloud.google.com/gke-nodepool: web-pool
          containers:
          - name: sd-covid-dashboard-crawler
            image: flrs/sd_covid_dashboard_crawler:latest
            env:
              - name: DB_HOST
                valueFrom:
                  secretKeyRef:
                    name: postgres-credentials
                    key: db_host
              - name: DB_NAME
                valueFrom:
                  secretKeyRef:
                    name: postgres-credentials
                    key: db_name
              - name: DB_USER
                valueFrom:
                  secretKeyRef:
                    name: postgres-credentials
                    key: db_user
              - name: DB_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: postgres-credentials
                    key: db_pass
          restartPolicy: OnFailure