apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

patchesStrategicMerge:
  - dashboard-deployment-env.yaml
  - crawler-cronjob-env.yaml
  - dashboard-service.yaml

resources:
  - postgres-secrets.yaml
  - kubeip
  - traefik