apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

patchesStrategicMerge:
  - dashboard-deployment-env.yaml
  - crawler-cronjob-env.yaml
  - dashboard-service.yaml

resources:
  - postgres-secrets.yaml
  - kubeip/configmap.yaml
  - kubeip/deployment.yaml
  - kubeip/serviceaccount.yaml
  - traefik/configmap.yaml
  - traefik/deployment.yaml
  - traefik/namespace.yaml
  - traefik/resource.yaml
  - traefik/route.yaml
  - traefik/secret.yaml
  - traefik/serviceaccount.yaml