apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

patchesStrategicMerge:
  - dashboard-deployment.yaml

resources:
  - dashboard-namespace.yaml
  - dashboard-service.yaml
  - postgres-secrets.yaml
  - crawler-cronjob.yaml
  - crawler-seedjob.yaml
  - kubeip/configmap.yaml
  - kubeip/deployment.yaml
  - kubeip/serviceaccount.yaml
  - kubeip/secret.yaml
  - traefik/namespace.yaml
  - traefik/resource.yaml
  - traefik/serviceaccount.yaml
  - traefik/deployment.yaml
  - traefik/route.yaml
  # Below may only work in newer versions of kustomization: https://github.com/kubernetes-sigs/kustomize/pull/2167
  # Currently, these resources get deployed in .github/workflows/deploy_app_gke.yml
  # - https://raw.githubusercontent.com/hiddeco/cronjobber/master/deploy/crd.yaml
  # - https://raw.githubusercontent.com/hiddeco/cronjobber/master/deploy/rbac.yaml
  # - https://raw.githubusercontent.com/hiddeco/cronjobber/master/deploy/deploy.yaml
  # - https://raw.githubusercontent.com/hiddeco/cronjobber/master/deploy/deploy-updatetz.yaml
  # - crawler-cronjob.yaml
