apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

patchesStrategicMerge:
  - dashboard-deployment.yaml

resources:
  - dashboard-namespace.yaml
  - dashboard-service.yaml
  - postgres-secrets.yaml
  - kubeip/configmap.yaml
  - kubeip/deployment.yaml
  - kubeip/serviceaccount.yaml
  - kubeip/secret.yaml
  - traefik/namespace.yaml
  - traefik/resource.yaml
  - traefik/serviceaccount.yaml
  - traefik/deployment.yaml
  - traefik/route.yaml
  - http://github.com/hiddeco/cronjobber/master/deploy/crd.yaml
  - http://github.com/hiddeco/cronjobber/master/deploy/rbac.yaml
  - http://github.com/hiddeco/cronjobber/master/deploy/deploy.yaml
  - http://github.com/hiddeco/cronjobber/master/deploy/deploy-updatetz.yaml
  - crawler-cronjob.yaml
  #- traefik/configmap.yaml
  #- traefik/secret.yaml
