name: sd_covid_dashboard_crawler
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - pandas=1.1
  - python=3.8.5
  - psycopg2=2.8
  - requests=2.24
  - PyPDF2=1.26
  - pip
  - tabula-py
  - pip:
    - waybackpack

