apiVersion: batch/v1
kind: Job
metadata:
  name: crawler-seedjob
spec:
  template:
    spec:
      containers:
      - name: sd-covid-dashboard-crawler-seedjob
        image: flrs/sd_covid_dashboard_crawler
        env:
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-credentials
                key: password
          - name: DB_HOST
            value: postgres-service
          - name: SEED_ONLY
            value: "true"
      restartPolicy: OnFailure