apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: crawler-cronjob
  namespace: dashboard
spec:
  schedule: "0 18 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: sd-covid-dashboard-crawler
            image: flrs/sd_covid_dashboard_crawler
          restartPolicy: OnFailure
