apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: crawler-cronjob
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: sd-covid-dashboard-crawler
              env:
                - name: DB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: postgres-credentials
                      key: password
                - name: DB_HOST
                  value: postgres-service
