name: Build Docker Crawler

on:
  push:
    branches: main
    paths:
     - crawler/**

env:
  MICROBADGER_WEBHOOK: https://hooks.microbadger.com/images/flrs/sd_covid_dashboard_crawler/3v5rphySV0sHEArO61yGVJyanEU=

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build and push Docker images
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
          repository: flrs/sd_covid_dashboard_crawler
          path: crawler
          tags: latest
          tag_with_sha: true
          tag_with_ref: true
          add_git_labels: true

      - name: Update MicroBadger
        uses: fjogeleit/http-request-action@master
          with:
            url: ${{ env.MICROBADGER_WEBHOOK }}
            method: 'POST'
