name: Deploy App on GKE

on:
  workflow_dispatch:
  push:
    branches: main
    paths:
     - .github/workflows/deploy_on_gke.yml
  workflow_run:
    workflows: [ "Build Docker Dashboard", "Build Docker Crawler" ]
    branches: [ main ]
    types:
      - completed

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  SECRETS_PASSPHRASE: ${{ secrets.SECRETS_KEY }}
  PROD_SECRETS_PASSPHRASE: ${{ secrets.PROD_SECRETS_KEY }}
  GKE_CLUSTER: sd-covid-dashboard-cluster
  GKE_ZONE: us-central1-c

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '290.0.1'
        service_account_key: ${{ secrets.GKE_SA_KEY }}
        project_id: ${{ secrets.GKE_PROJECT }}

    - run: |-
        gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"

    - name: Set up kubectl
      run: |-
        sudo apt-get update && sudo apt-get install -y apt-transport-https gnupg2
        curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
        echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee -a /etc/apt/sources.list.d/kubernetes.list
        sudo apt-get update
        sudo apt-get install -y kubectl

    - name: Decrypt secrets
      run: |-
        gpg --batch --yes --passphrase="$PROD_SECRETS_PASSPHRASE" --decrypt --output k8s/overlays/prod/postgres-secrets.yaml k8s/overlays/prod/postgres-secrets.yaml.enc

    - name: Show workflow
      run: |-
        echo "${{ fromJSON(github.event_path).workflow.name }}"

    - name: Update dashboard image
      if: fromJSON(${{ github.event_path }}).workflow.name == 'Build Docker Dashboard'
      id: deploy_dashboard
      run: |-
        export SHORT_SHA=$(git rev-parse --short ${{ github.sha }})
        kubectl config current-context
        kubectl set image deployment/dashboard sd-covid-dashboard-dashboard=flrs/sd_covid_dashboard_dashboard:sha-$SHORT_SHA

    - name: Update crawler image
      if: fromJSON(${{ github.event_path }}).workflow.name == 'Build Docker Crawler'
      id: deploy_crawler
      run: |-
        export SHORT_SHA=$(git rev-parse --short ${{ github.sha }})
        kubectl config current-context
        kubectl set image cronjob/crawler-cronjob sd-covid-dashboard-crawler=flrs/sd_covid_dashboard_crawler:sha-$SHORT_SHA

    - name: Deploy whole app
      if: steps.deploy_dashboard.outcome == 'skipped' && steps.deploy_crawler.outcome == 'skipped'
      run: |-
        kubectl config current-context
        kubectl apply -k k8s/overlays/prod
        kubectl create job --from=cronjob/crawler-cronjob crawler-database-seeding
